version: '3'

services:
    ci_test:
        build:
            context: .
        environment:
            - CI=true
        command: yarn test

    local_test:
        build:
            context: .
        command: yarn test --watchAll
        volumes:
            - './src:/app/src'
